### ISSUE TITLE
"bandwidth test failed: EOF" Could use better messaging 

### ISSUE THREAD

**Issue by zackkitzmiller** [traetox/speedtest#1]
I haven't looked into this very deeply yet, but I believe this error messaging could be improved.

```
Gathering server list and testing...
5 Closest responding servers:
-------  ----------------------  ---------------------  ------------------  -----------------
    ID                    Name                Sponsor       Distance (km)       Latency (ms)
-------  ----------------------  ---------------------  ------------------  -----------------
     0       New York City, NY                Inerail                9.91        18.831639ms

     1       New York City, NY         Optimum Online                9.91        21.401682ms

     2       New York City, NY         Atlantic Metro                9.91        24.010309ms

     3            Secaucus, NJ       Interserver, inc               18.37        26.194842ms

     4             Clifton, NJ            FortressITX               28.40        19.171797ms
-------  ----------------------  ---------------------  ------------------  -----------------
Enter server ID for bandwidth test, or "quit" to exit
ID> 2
Latency: ▃▂█▆▃▆▃▁▁▃▄▃▁▂▆▂█▃▁▃   21ms avg    24ms median 39ms max    12ms min
bandwidth test failed: EOF
```

**Comment by hwinkel** [comment]
I get an EOF even before the tests starts

**Comment by traetox** [comment]
I am seeing the same thing, I think an API changed.  I will get it fixed.

On Fri, Jan 29, 2016 at 2:14 PM, Holger Winkelmann <notifications@github.com
> wrote:

> I get an EOF even before the tests starts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traetox/speedtest/issues/1#issuecomment-176971859>.
>



-- 
:ZZ

**Comment by traetox** [comment]
fixed.

On Fri, Jan 29, 2016 at 2:22 PM, K. Watts <traetox@gmail.com> wrote:

> I am seeing the same thing, I think an API changed.  I will get it fixed.
>
> On Fri, Jan 29, 2016 at 2:14 PM, Holger Winkelmann <
> notifications@github.com> wrote:
>
>> I get an EOF even before the tests starts
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/traetox/speedtest/issues/1#issuecomment-176971859>.
>>
>
>
>
> --
> :ZZ
>



-- 
:ZZ

**Comment by hwinkel** [comment]
thanks
