### ISSUE TITLE
Test failed with unknown error: dial tcp 193.200.42.217:8080: i/o timeout

### ISSUE THREAD

**Issue by nlamirault** [traetox/speedtest#4]
Hi,
i try to test bandwidth using French server, i've got an error on severals servers:

```bash
$ speedtest -s="Paris"
9 Matching servers:
-------  ----------  ---------------------------------  ------------------
    ID        Name                            Sponsor       Distance (km) 
-------  ----------  ---------------------------------  ------------------
     0       Paris                         FreeMobile              461.09 

     1       Paris                        NEOTELECOMS              461.09 

     2       Paris                             Orange              461.09 

     3       Paris                          Cloudwatt              461.09 

     4       Paris                                SFR              461.09 

     5       Paris                   Bouygues Telecom              461.09 

     6       Paris                     fdcservers.net              461.09 

     7       Paris       SoftLayer Technologies, Inc.              461.09 

     8       Paris                 MEDIACTIVE NETWORK              461.09 
-------  ----------  ---------------------------------  ------------------
Enter server ID for bandwidth test, or "quit" to exit
ID> 2
Test failed with unknown error: dial tcp 193.200.42.217:8080: i/o timeout
```

**Comment by traetox** [comment]
The error stems from a time timeout on the connection attempt, so either the server is down or there is something preventing you from connecting to it (or its rejecting the connection attempt).  I just hit the particular server and got a successful test, I am dramatically further away than you so if you wouldn't mind repulling and retesting I would appreciate it.

The error message is admittedly terrible, so I pushed a commit to try to make it more clear.

**Comment by nlamirault** [comment]
I just download a fresh version.
I've got this error : 

Test failed due to connection timeout.  The server may be down, or rejecting us

**Comment by traetox** [comment]
might be a legit connectivity issue.  Try to just straight up connect to
the server in question.  if you run:

nc -vvv 193.200.42.217 8080

Does it show that the connection timed out? or do you get a successful
connection?  It should output something like:

paris1.speedtest.orange.fr [193.200.42.217] 8080 (http-alt) open


The error is literally saying "I tried to connect and the server never
responded."


Not really an error with the application that I can test or replicate.

On Mon, Feb 22, 2016 at 10:41 AM, Nicolas Lamirault <
notifications@github.com> wrote:

> I just download a fresh version.
> I've got this error :
>
> Test failed due to connection timeout. The server may be down, or
> rejecting us
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traetox/speedtest/issues/4#issuecomment-187284644>.
>



-- 
:ZZ

**Comment by nlamirault** [comment]
no response : 
```
$ nc -zv 193.200.42.217 8080
```

**Comment by traetox** [comment]
When I run that from the States the port is open and the server responds.
Looks like paris1.speedtest.orage.fr is not happy with your source subnet.

Thanks for using the tool and submitting issues.  I appreciate the
feedback, especially on usability problems.

On Mon, Feb 22, 2016 at 10:56 AM, Nicolas Lamirault <
notifications@github.com> wrote:

> no response :
>
> $ nc -zv 193.200.42.217 8080
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traetox/speedtest/issues/4#issuecomment-187294132>.
>



-- 
:ZZ

**Comment by nlamirault** [comment]
After updating firewall rules it works. Thanks
